pipeline {
    agent any

    environment {
        IMAGE_NAME = "dharshinikarnan/devops-nodejs-app"
        IMAGE_TAG  = "1.0"
        EC2_HOST   = "13.127.149.214"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    bat """
                    docker build -t %IMAGE_NAME%:%IMAGE_TAG% .
                    """
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat """
                    docker login -u %DOCKER_USER% -p %DOCKER_PASS%
                    docker push %IMAGE_NAME%:%IMAGE_TAG%
                    """
                }
            }
        }

        stage('Deploy to AWS EC2') {
            steps {
                withCredentials([
                    sshUserPrivateKey(
                        credentialsId: 'ec2-ssh-key',
                        keyFileVariable: 'SSH_KEY',
                        usernameVariable: 'SSH_USER'
                    )
                ]) {
                    bat """
                    ssh -o StrictHostKeyChecking=no -i %SSH_KEY% %SSH_USER%@%EC2_HOST% ^
                    "docker pull %IMAGE_NAME%:%IMAGE_TAG% && ^
                     docker stop devops-nodejs-app || docker rm devops-nodejs-app || exit 0 && ^
                     docker run -d -p 3000:3000 --name devops-nodejs-app %IMAGE_NAME%:%IMAGE_TAG%"
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD Pipeline completed successfully!"
        }
        failure {
            echo "❌ CI/CD Pipeline failed!"
        }
    }
}
