pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dharshinikarnan/devops-nodejs-app"
        DOCKER_TAG   = "1.0"
        EC2_HOST     = "13.127.149.214"
        EC2_USER     = "ubuntu"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    bat "docker build -t %DOCKER_IMAGE%:%DOCKER_TAG% ."
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat """
                    docker login -u %DOCKER_USER% -p %DOCKER_PASS%
                    docker push %DOCKER_IMAGE%:%DOCKER_TAG%
                    """
                }
            }
        }

        stage('Deploy to AWS EC2') {
            steps {
                withCredentials([
                    sshUserPrivateKey(
                        credentialsId: 'ec2-ssh-key',
                        keyFileVariable: 'SSH_KEY'
                    )
                ]) {
                    bat """
                    ssh -o StrictHostKeyChecking=no -i %SSH_KEY% %EC2_USER%@%EC2_HOST% ^
                    "docker pull %DOCKER_IMAGE%:%DOCKER_TAG% && ^
                     docker stop devops-nodejs-app || true && ^
                     docker rm devops-nodejs-app || true && ^
                     docker run -d -p 3000:3000 --name devops-nodejs-app %DOCKER_IMAGE%:%DOCKER_TAG%"
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD Pipeline completed successfully!"
        }
        failure {
            echo "❌ CI/CD Pipeline failed!"
        }
    }
}
